ServerUri = "127.0.0.1"
Port = 1883
#  MQTT protocol version to use ("V311", "V310" or "V500")
MqttVersion = "V500"            
Username = ""
Password = ""
ConnectionTimeOut = 1
KeepAlivePeriod = 60
CleanSession = true
#  number of clients to use for the benchmark
ClientCount = 50
#  number of messages to send from each client
MessageCount = 10000
#  size of each message in bytes
MessageSize = 100
#  quality of service level to use for message delivery (0, 1 or 2)
Qos = 0                         
Retain = false
